    <?php 
        $students = [
            [
                "firstName" => "James",
                "lastName" => "Fields",
                "grades" => [12, 11, 15],
                "average" => -1
            ],
            [
                "firstName" => "Richard",
                "lastName" => "Stein",
                "grades" => [18, 12, 13],
                "average" => -1
            ],
            [
                "firstName" => "Mark",
                "lastName" => "Hartoff",
                "grades" => [9, 11, 10],
                "average" => -1
            ],
            [
                "firstName" => "Thomas",
                "lastName" => "Nestle",
                "grades" => [9, 8, 5],
                "average" => -1
            ],
            [
                "firstName" => "Jeremy",
                "lastName" => "Brent",
                "grades" => [18, 15, 16],
                "average" => -1
            ]
        ];
        
        function average(array $grades) :float {
            $sum = 0;
            foreach($grades as $note)
            {
                $sum+=$note;
            }
            return round($sum / count($grades), 1);
        }
        
        function changeColor(float $averages):string
        {
            if($averages<10){
                return "red";
            }
            else if ($averages>=10 && $averages<=13){
                 
                return "orange";
            }
            else if ($averages>13){
                return "green";
            }
        }
    ?>

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="" />
    <meta name="referrer" content="origin" />
    <meta name="title" content="">
    <meta name="keywords" content="">
    <meta property="og:site_name" content="">
    <meta property="og:title" content="">
    <meta property="og:type" content="article">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta property="og:locale" content="fr_FR">
    <link rel="stylesheet" href="style.css">
    <title>Titre</title>
</head>

<body>
    <header>

    </header>
    <main>
        <?php foreach($students as $student){ ?>
        
        <article class="<?php echo changeColor(average($student["grades"]))?>">
            <header>
                <h1><?php echo "{$student["firstName"]} {$student["lastName"]}"?></h1>
            </header>
            <section>
                <h2>Notes : </h2>
                <ul>
                    <?php foreach($student["grades"] as $grade){ ?>
                    <li><?php echo "{$grade}" ?></li>
                    <?php } ?>
                </ul>
            </section>
            <footer>
                <h3><?= average($student["grades"]) ?></h3>
                
            </footer>
        </article>
        
        <?php }; ?>
    </main>
    <footer>

    </footer>
</body>

</html>
