<!DOCTYPE html>

    <?php 
        $students = [
            [
                "firstName" => "James",
                "lastName" => "Fields",
                "grades" => [12, 11, 15],
                "average" => -1
            ],
            [
                "firstName" => "Richard",
                "lastName" => "Stein",
                "grades" => [18, 12, 13],
                "average" => -1
            ],
            [
                "firstName" => "Mark",
                "lastName" => "Hartoff",
                "grades" => [9, 11, 10],
                "average" => -1
            ],
            [
                "firstName" => "Thomas",
                "lastName" => "Nestle",
                "grades" => [9, 8, 5],
                "average" => -1
            ],
            [
                "firstName" => "Jeremy",
                "lastName" => "Brent",
                "grades" => [18, 15, 16],
                "average" => -1
            ]
        ];
    ?>


<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="" />
    <meta name="referrer" content="origin" />
    <meta name="title" content="">
    <meta name="keywords" content="">
    <meta property="og:site_name" content="">
    <meta property="og:title" content="">
    <meta property="og:type" content="article">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta property="og:locale" content="fr_FR">
    <link rel="stylesheet" href="assets/styles/css/style.css">
    <title></title>
</head>

<body>
    <header>

    </header>
    <main>
        <?php foreach($students as $student){ ?>
        
         <article class="">
            <header>
                <h1><?php echo "{$student["firstName"]} {$student["lastName"]}"?></h1>
            </header>
            <section>
                <h2>Notes : </h2>
                <ul>
                    <?php for(){
                        
                    }?>
                    <li></li>
                    <li>Note 2</li>
                    <li>Note 3</li>
                </ul>
            </section>
            <footer>
                <h3>Moyenne des notes de l'étudiant </h3>
            </footer>
        </article>
        
        <?php }; ?>
    </main>
    <footer>

    </footer>
</body>

</html>
